#include "generation/sol2_generator.hpp"

namespace
{
    void write_line(std::ofstream& out, int indent, const std::string& text, int newlines = 1)
    {
        out << std::string(indent * 4, ' ') << text << std::string(std::max(0, newlines), '\n');
    }
}

namespace codegen::generation
{
    void Sol2Generator::generate(const std::unordered_set<std::string>& includes,
                                 const std::vector<metadata::ClassDescriptor>& classes,
                                 const std::vector<metadata::FunctionDescriptor>& free_functions,
                                 const std::vector<metadata::EnumDescriptor>& enums) const
    {
        std::ofstream out(output_file_);
        if (!out.is_open())
        {
            std::cerr << "Failed to open output file: " << output_file_ << std::endl;
            return;
        }

        write_header(out, includes);
        write_member_registrations(out, classes);
        write_non_member_registrations(out, free_functions, enums);
        write_footer(out);
    }

    void Sol2Generator::write_header(std::ofstream& out, const std::unordered_set<std::string>& includes)
    {
        write_line(out, 0, "// This file is auto-generated by the code generator. Do not edit manually!", 2);
        write_line(out, 0, "#include \"bindings/lua/lua_binder.hpp\"");
        write_line(out, 0, "#include \"bindings/lua/member_registrar.hpp\"");
        write_line(out, 0, "#include \"bindings/lua/non_member_registrar.hpp\"", 2);

        for (const auto& include : includes)
        {
            write_line(out, 0, std::format("#include <{}>", include));
        }
        write_line(out, 0, "");
        write_line(out, 0, "#include <sol/sol.hpp>", 2);
        write_line(out, 0, "using namespace ogdf;", 2);
        write_line(out, 0, "namespace engine::bindings::lua");
        write_line(out, 0, "{");
    }

    void Sol2Generator::write_member_registrations(std::ofstream& out, const std::vector<metadata::ClassDescriptor>& classes)
    {
        write_line(out, 1, "void register_members(sol::state& lua)");
        write_line(out, 1, "{");

        std::unordered_set<std::string> registered_bases;
        for (const auto& cls : classes)
        {
            for (const auto& base_name : cls.base_class_names())
            {
                if (registered_bases.find(base_name) == registered_bases.end())
                {
                    write_line(out, 2, std::format("MemberRegistrar<{}, MemoryOwnership::Cpp>(lua, \"{}\");", base_name, base_name));
                    registered_bases.insert(base_name);
                }
            }
        }

        if (!registered_bases.empty())
        {
            write_line(out, 0, "");
        }

        for (const auto& cls : classes)
        {
            std::string ownership = cls.constructors().empty() ? "Cpp" : "Lua";
            write_line(out, 2, std::format("MemberRegistrar<{}, MemoryOwnership::{}>(lua, \"{}\")", cls.name(), ownership, cls.name()));

            if (!cls.constructors().empty())
            {
                std::stringstream ss;
                for (size_t i = 0; i < cls.constructors().size(); ++i)
                {
                    auto signature = cls.constructors()[i].signature();
                    if (signature.front() == '(' && signature.back() == ')')
                    {
                        signature = signature.substr(1, signature.length() - 2);
                    }
                    ss << "sol::types<" << signature << ">" << (i < cls.constructors().size() - 1 ? ", " : "");
                }
                write_line(out, 3, std::format(".add_shared_constructors<{}>()", ss.str()));
            }

            if (!cls.base_class_names().empty())
            {
                std::stringstream ss;
                for (size_t i = 0; i < cls.base_class_names().size(); ++i)
                {
                    ss << cls.base_class_names()[i] << (i < cls.base_class_names().size() - 1 ? ", " : "");
                }
                write_line(out, 3, std::format(".add_bases<{}>()", ss.str()));
            }

            for (const auto& var : cls.member_variables())
            {
                if (var.is_static())
                {
                    write_line(out, 3, std::format(".add_static_variable(\"{}\", {}::{})", var.name(), cls.name(), var.name()));
                }
                else
                {
                    write_line(out, 3, std::format(".add_variable(\"{}\", &{}::{}, {})", var.name(), cls.name(), var.name(), var.is_const()));
                }
            }

            std::map<std::string, std::vector<const metadata::FunctionDescriptor*>> overloads;
            for (const auto& func : cls.member_functions())
            {
                overloads[func.name()].emplace_back(&func);
            }

            for (const auto& [name, funcs] : overloads)
            {
                std::stringstream ss;
                for (size_t i = 0; i < funcs.size(); ++i)
                {
                    if (funcs.size() == 1)
                    {
                        ss << "&" << cls.name() << "::" << funcs[i]->name();
                    }
                    else
                    {
                        if (funcs[i]->is_const())
                        {
                            ss << "sol::resolve<" << funcs[i]->return_type_name() << funcs[i]->signature() << " const>(";
                        }
                        else
                        {
                            ss << "sol::resolve<" << funcs[i]->return_type_name() << funcs[i]->signature() << ">(";
                        }
                        ss << "&" << cls.name() << "::" << funcs[i]->name() << ")" << (i < funcs.size() - 1 ? ", " : "");
                    }
                }
                write_line(out, 3, std::format(".add_functions(\"{}\", {})", name, ss.str()));
            }

            write_line(out, 2, ";", 2);
        }
        write_line(out, 1, "}", 2);
    }

    void Sol2Generator::write_non_member_registrations(std::ofstream& out,
                                                  const std::vector<metadata::FunctionDescriptor>& free_functions,
                                                  const std::vector<metadata::EnumDescriptor>& enums)
    {
        write_line(out, 1, "void register_non_members(sol::state& lua)");
        write_line(out, 1, "{");
        write_line(out, 2, "NonMemberRegistrar registrar(lua);", 2);

        for (const auto& func : free_functions)
        {
            write_line(out, 2, std::format("registrar.add_function(\"{}\", &{});", func.name(), func.name()), 3);
        }

        for (const auto& enum_ : enums)
        {
            std::stringstream ss;
            for (size_t i = 0; i < enum_.enumerators().size(); ++i)
            {
                const auto& enumerator = enum_.enumerators()[i];
                ss << "\"" << enumerator.name << "\", " << enum_.name() << "::" << enumerator.name;
                if (i < enum_.enumerators().size() - 1) ss << ", ";
            }
            write_line(
                out, 2, std::format("registrar.add_enums<{}>(\"{}\", {});", enum_.name(), enum_.name(), ss.str()));
        }

        write_line(out, 1, "}");
    }

    void Sol2Generator::write_footer(std::ofstream& out)
    {
        write_line(out, 0, "} // namespace engine::bindings::lua");
    }
} // namespace codegen::generation
