#include "generation/sol2_generator.hpp"

namespace
{
    void write_line(std::ofstream& out, int indent, const std::string& text, int newlines = 1)
    {
        out << std::string(indent * 4, ' ') << text << std::string(std::max(0, newlines), '\n');
    }
}

namespace codegen::generation
{
    void Sol2Generator::generate(const std::unordered_set<std::string>& includes,
                                 const std::vector<metadata::ClassDescriptor>& classes,
                                 const std::vector<metadata::FunctionDescriptor>& free_functions,
                                 const std::vector<metadata::EnumDescriptor>& enums) const
    {
        std::ofstream out(output_file_);
        if (!out.is_open())
        {
            std::cerr << "Failed to open output file: " << output_file_ << std::endl;
            return;
        }

        write_header(out, includes);
        write_member_registrations(out, classes);
        write_non_member_registrations(out, free_functions, enums);
        write_footer(out);
    }

    void Sol2Generator::write_header(std::ofstream& out, const std::unordered_set<std::string>& includes)
    {
        write_line(out, 0, "// This file is auto-generated by the code generator. Do not edit manually!", 2);
        write_line(out, 0, "#include \"bindings/lua/lua_binder.hpp\"");
        write_line(out, 0, "#include \"bindings/lua/member_registrar.hpp\"");
        write_line(out, 0, "#include \"bindings/lua/non_member_registrar.hpp\"", 2);

        for (const auto& include : includes)
        {
            write_line(out, 0, std::format("#include <{}>", include));
        }
        write_line(out, 0, "");
        write_line(out, 0, "#include <sol/sol.hpp>", 2);
        write_line(out, 0, "using namespace ogdf;", 2);
        write_line(out, 0, "namespace engine::bindings::lua");
        write_line(out, 0, "{");
    }

    void Sol2Generator::write_member_registrations(std::ofstream& out, const std::vector<metadata::ClassDescriptor>& classes)
    {
        write_line(out, 1, "void register_members(sol::state& lua)");
        write_line(out, 1, "{");

        auto lua_name_formatter = [](std::string name)
        {
            size_t start_pos = name.find('<');
            if (start_pos != std::string::npos)
            {
                size_t end_pos = name.rfind('>');
                if (end_pos != std::string::npos)
                {
                    name.replace(start_pos, 1, "_");
                    name.erase(end_pos, 1);
                }
            }
            return name;
        };

        std::unordered_set<std::string> target_class_names;
        for (const auto& cls : classes)
        {
            target_class_names.emplace(cls.name());
        }

        std::unordered_set<std::string> registered_bases;
        for (const auto& cls : classes)
        {
            for (const auto& base_name : cls.base_class_names())
            {
                if (target_class_names.contains(base_name))
                {
                    continue;
                }

                if (!registered_bases.contains(base_name))
                {
                    std::string lua_base_name = lua_name_formatter(base_name);
                    write_line(out, 2, std::format("MemberRegistrar<{}, MemoryOwnership::Cpp>(lua, \"{}\");", base_name, lua_base_name));
                    registered_bases.emplace(base_name);
                }
            }
        }

        if (!registered_bases.empty())
        {
            write_line(out, 0, "");
        }

        for (const auto& cls : classes)
        {
            std::string lua_name = lua_name_formatter(cls.name());
            std::string ownership = cls.constructors().empty() ? "Cpp" : "Lua";
            write_line(out, 2, std::format("MemberRegistrar<{}, MemoryOwnership::{}>(lua, \"{}\")", cls.name(), ownership, lua_name));

            if (!cls.constructors().empty())
            {
                std::string constructor_types;
                for (size_t i = 0; i < cls.constructors().size(); ++i)
                {
                    auto signature = cls.constructors()[i].signature();
                    if (signature.front() == '(' && signature.back() == ')')
                    {
                        signature = signature.substr(1, signature.length() - 2);
                    }
                    constructor_types += std::format("sol::types<{}>", signature);
                    if (i < cls.constructors().size() - 1)
                    {
                        constructor_types += ", ";
                    }
                }
                write_line(out, 3, std::format(".add_shared_constructors<{}>()", constructor_types));
            }

            if (!cls.base_class_names().empty())
            {
                std::string bases_str;
                for (size_t i = 0; i < cls.base_class_names().size(); ++i)
                {
                    bases_str += cls.base_class_names()[i];
                    if (i < cls.base_class_names().size() - 1)
                    {
                        bases_str += ", ";
                    }
                }
                write_line(out, 3, std::format(".add_bases<{}>()", bases_str));
            }

            for (const auto& var : cls.member_variables())
            {
                if (var.is_static())
                {
                    write_line(out, 3, std::format(".add_static_variable(\"{}\", {}::{})", var.name(), cls.name(), var.name()));
                }
                else
                {
                    write_line(out, 3, std::format(".add_variable(\"{}\", &{}::{}, {})", var.name(), cls.name(), var.name(), var.is_const()));
                }
            }

            std::map<std::string, std::vector<const metadata::FunctionDescriptor*>> overloads;
            for (const auto& func : cls.member_functions())
            {
                overloads[func.name()].emplace_back(&func);
            }

            for (const auto& [name, funcs] : overloads)
            {
                std::string overload_expressions;
                if (funcs.size() == 1)
                {
                    overload_expressions += std::format("&{}::{}", cls.name(), funcs[0]->name());
                }
                else
                {
                    std::vector<std::string> expressions;
                    expressions.reserve(funcs.size());
                    for (const auto& func : funcs)
                    {
                        if (func->is_const())
                        {
                            expressions.emplace_back(std::format("sol::resolve<{}{} const>(&{}::{})",
                                                                 func->return_type_name(), func->signature(),
                                                                 cls.name(), func->name()));
                        }
                        else
                        {
                            expressions.emplace_back(std::format("sol::resolve<{}{}>(&{}::{})",
                                                                 func->return_type_name(), func->signature(),
                                                                 cls.name(), func->name()));
                        }
                    }

                    std::string joiner = ",\n\t\t\t\t";
                    for (size_t i = 0; i < expressions.size(); ++i)
                    {
                        overload_expressions += expressions[i];
                        if (i < expressions.size() - 1)
                        {
                            overload_expressions += joiner;
                        }
                    }
                }
                write_line(out, 3, std::format(".add_functions(\"{}\", {})", name, overload_expressions));
            }
            write_line(out, 2, ";", 2);
        }
        write_line(out, 1, "}", 2);
    }

    void Sol2Generator::write_non_member_registrations(std::ofstream& out,
                                                       const std::vector<metadata::FunctionDescriptor>& free_functions,
                                                       const std::vector<metadata::EnumDescriptor>& enums)
    {
        write_line(out, 1, "void register_non_members(sol::state& lua)");
        write_line(out, 1, "{");
        write_line(out, 2, "NonMemberRegistrar registrar(lua);", 2);

        for (const auto& func : free_functions)
        {
            write_line(out, 2, std::format("registrar.add_function(\"{}\", &{});", func.name(), func.name()));
        }

        for (const auto& enum_ : enums)
        {
            std::vector<std::string> enumerator_pairs;
            enumerator_pairs.reserve(enum_.enumerators().size());
            for (const auto& enumerator : enum_.enumerators())
            {
                enumerator_pairs.emplace_back(std::format("\"{}\", {}::{}", enumerator.name, enum_.name(), enumerator.name));
            }

            std::string enumerators_str;
            for (size_t i = 0; i < enumerator_pairs.size(); ++i)
            {
                enumerators_str += enumerator_pairs[i];
                if (i < enumerator_pairs.size() - 1)
                {
                    enumerators_str += ", ";
                }
            }
            write_line(out, 2, std::format("registrar.add_enums<{}>(\"{}\", {});", enum_.name(), enum_.name(), enumerators_str));
        }
        write_line(out, 1, "}");
    }

    void Sol2Generator::write_footer(std::ofstream& out)
    {
        write_line(out, 0, "} // namespace engine::bindings::lua");
    }
} // namespace codegen::generation
