function(load_env_file env_file)
    if (EXISTS ${env_file})
        file(STRINGS ${env_file} env_vars)
        foreach (env_var ${env_vars})
            if (env_var MATCHES "^[^#]" AND NOT env_var STREQUAL "")
                if (env_var MATCHES "^([^=]+)=(.*)$")
                    set(var_name "${CMAKE_MATCH_1}")
                    set(var_value "${CMAKE_MATCH_2}")
                    set(${var_name} "${var_value}" PARENT_SCOPE)
                    message(STATUS "Loaded from .env: ${var_name}=${var_value}")
                endif ()
            endif ()
        endforeach ()
    else ()
        message(WARNING "No .env file found at ${env_file}. Copy .env.example to .env and configure your environment variables.")
    endif ()
endfunction()